name: beatbox_app
description: A drum box for beatbox in Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'El_Giancar' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  fluttertoast: ^7.1.1
  flutter_sound_lite: ^6.4.8+2
  intl: 0.17.0-nullsafety.2
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl: 0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

flutter_intl:
  main_locale: en_US
  enabled: true
